name: Greetings

on: [push, pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: copy dist/ to doc/ for ghpages
      run: |
           rm -rf doc
           cp -r dist doc

      # Runs a set of commands using the runners shell
    - name: commit built site
      run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add .
         if ! git diff-index --quiet HEAD --; then
            git commit -m "Autobuild webpack TS site github action commit"
            git push
            echo "pushing changes"
         fi           
